renderer:
  preset:
    class_path: fhir_pydantic_project.FHIRPydanticPreset
  output_dir: generated/ccda-on-fhir-pydantic
  variables:
    project_name: ccda-on-fhir-pydantic
    package_name: ccda_on_fhir_pydantc
definitions:
  class_path: fhir_gen.Definitions
  init_args:
    url: https://build.fhir.org/ig/HL7/ccda-on-fhir/definitions.json.zip
    version: 1.2.0
    sources:
      - StructureDefinition-US-Realm-Header.json
parser:
  base_url: http://hl7.org/ccda-on-fhir
  mappings:
    "http://hl7.org/fhirpath/System.String": http://hl7.org/fhir/StructureDefinition/string
  