rendering:
  template: templates/pydantic_project
  output_dir: generated/fhir-r5-pydantic
  variables:
    project_name: fhir-r5-pydantic
    package_name: fhir_pydantic
definitions:
  class_path: fhir_gen.Definitions
  init_args:
    url: https://build.fhir.org/ig/HL7/ccda-on-fhir/definitions.json.zip
    version: 1.2.0
    sources:
      - StructureDefinition-US-Realm-Header.json
mappings:
  "http://hl7.org/fhirpath/System.String": builtins.str
  