renderer:
  preset:
    class_path: fhir_pydantic_project.FHIRPydanticPreset
  output_dir: generated/fhir-r5-pydantic
  variables:
    project_name: fhir-r5-pydantic
    package_name: fhir_pydantic
definitions:
  class_path: fhir_gen.Definitions
  init_args:
    url: https://hl7.org/fhir/R5/definitions.json.zip
    version: R5
    sources:
      - dataelements.json
      - valuesets.json
      - profiles-types.json
      - profiles-resources.json
parser:
  base_url: http://hl7.org/fhir
  mappings:
    "http://hl7.org/fhirpath/System.String": http://hl7.org/fhir/StructureDefinition/string
  